# Generated by Django 3.2.20 on 2023-07-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weseeu', '0002_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
