# Generated by Django 3.2.20 on 2023-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weseeu', '0003_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
